name: Trigger auto deployment for nodeexpressbasics

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/nodeexpressbasics-AutoDeployTrigger-8e83623e-a358-4df2-b3e9-4eb8f47797a3.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca84c35ba906acr.azurecr.io
          username: ${{ secrets.NODEEXPRESSBASICS_REGISTRY_USERNAME }}
          password: ${{ secrets.NODEEXPRESSBASICS_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca84c35ba906acr.azurecr.io/nodeexpressbasics:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NODEEXPRESSBASICS_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n nodeexpressbasics -g album-containerapps --server ca84c35ba906acr.azurecr.io --username  ${{ secrets.NODEEXPRESSBASICS_REGISTRY_USERNAME }} --password ${{ secrets.NODEEXPRESSBASICS_REGISTRY_PASSWORD }}
            az containerapp update -n nodeexpressbasics -g album-containerapps --image ca84c35ba906acr.azurecr.io/nodeexpressbasics:${{ github.sha }}
